name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  flutter: ">=3.0.0 <4.0.0"
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  bloc: ^8.1.2
  eit_networking:
    hosted:
      url: https://gitea.prntes.space/api/packages/platform/pub/
      name: eit_networking
    version: ^2.0.0-beta.7
  eit_result:
    hosted:
      url: https://gitea.prntes.space/api/packages/platform/pub/
      name: eit_result
    version: ^1.0.0
  eit_storage:
    hosted:
      url: https://gitea.prntes.space/api/packages/platform/pub/
      name: eit_storage
    version: ^1.0.3
  eit_uikit:
    hosted:
      url: https://gitea.prntes.space/api/packages/mobi/pub/
      name: eit_uikit
    version: ^1.1.4-snapshot.13
  equatable: ^2.0.5
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  go_router: ^10.0.0
  json_annotation: ^4.8.1
  meta: ^1.9.1
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mason_tpl:
    path: ../
  test: ^1.21.0
  zoo_lints: ^3.0.0
