name: mason_tpl
description: >
  Generate templates from live app.

version: 1.0.0
repository: https://github.com/zoocityboy/mason_tpl

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  checked_yaml: ^2.0.3
  collection: ^1.17.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  mason_logger: ^0.2.8
  meta: ^1.9.1
  path: ^1.8.3
  universal_io: ^2.2.2
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.21.0
  zoo_lints: ^3.0.0
executables:
  mason_tpl:
  mtpl:
